import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { buildIgnoreFile } from '../src/generators/cursorignore.js';
import { generateClaudeSettings } from '../src/generators/claude-settings.js';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';

describe('buildIgnoreFile', () => {
  it('includes header with tool name', () => {
    const content = buildIgnoreFile('TestTool', '.testignore', ['.env']);
    expect(content).toContain('# .testignore');
    expect(content).toContain('TestTool');
  });

  it('includes warnings when provided', () => {
    const content = buildIgnoreFile('TestTool', '.testignore', [], ['Some warning']);
    expect(content).toContain('# WARNING: Some warning');
  });

  it('categorizes patterns into sections', () => {
    const patterns = ['.env', '*.pem', '.ssh/', '.aws/', 'vault.json'];
    const content = buildIgnoreFile('TestTool', '.testignore', patterns);
    expect(content).toContain('# Secrets & Environment');
    expect(content).toContain('# Keys & Certificates');
    expect(content).toContain('# SSH');
    expect(content).toContain('# Cloud Providers');
    expect(content).toContain('# Application Secrets & Database');
  });

  it('includes aiignore attribution', () => {
    const content = buildIgnoreFile('TestTool', '.testignore', []);
    expect(content).toContain('Generated by aiignore');
  });
});

describe('generateClaudeSettings', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'aiignore-claude-'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('creates settings.json with Read deny patterns', () => {
    const result = generateClaudeSettings(tmpDir, ['.env', '*.pem'], 'default');
    expect(result.created).toBe(true);

    const settings = JSON.parse(fs.readFileSync(path.join(tmpDir, '.claude', 'settings.json'), 'utf-8'));
    expect(settings.permissions.deny).toContain('Read(.env)');
    expect(settings.permissions.deny).toContain('Read(*.pem)');
  });

  it('preserves existing non-aiignore deny patterns', () => {
    const settingsDir = path.join(tmpDir, '.claude');
    fs.mkdirSync(settingsDir, { recursive: true });
    fs.writeFileSync(
      path.join(settingsDir, 'settings.json'),
      JSON.stringify({ permissions: { deny: ['Write(package.json)'] } }),
    );

    generateClaudeSettings(tmpDir, ['.env'], 'default');
    const settings = JSON.parse(fs.readFileSync(path.join(settingsDir, 'settings.json'), 'utf-8'));
    expect(settings.permissions.deny).toContain('Write(package.json)');
    expect(settings.permissions.deny).toContain('Read(.env)');
  });

  it('replaces aiignore patterns on --force', () => {
    const settingsDir = path.join(tmpDir, '.claude');
    fs.mkdirSync(settingsDir, { recursive: true });
    fs.writeFileSync(
      path.join(settingsDir, 'settings.json'),
      JSON.stringify({ permissions: { deny: ['Read(old-pattern)', 'Write(keep-this)'] } }),
    );

    generateClaudeSettings(tmpDir, ['.env'], 'force');
    const settings = JSON.parse(fs.readFileSync(path.join(settingsDir, 'settings.json'), 'utf-8'));
    expect(settings.permissions.deny).not.toContain('Read(old-pattern)');
    expect(settings.permissions.deny).toContain('Write(keep-this)');
    expect(settings.permissions.deny).toContain('Read(.env)');
  });

  it('preserves other settings fields', () => {
    const settingsDir = path.join(tmpDir, '.claude');
    fs.mkdirSync(settingsDir, { recursive: true });
    fs.writeFileSync(
      path.join(settingsDir, 'settings.json'),
      JSON.stringify({ model: 'opus', permissions: { allow: ['Bash'] } }),
    );

    generateClaudeSettings(tmpDir, ['.env'], 'default');
    const settings = JSON.parse(fs.readFileSync(path.join(settingsDir, 'settings.json'), 'utf-8'));
    expect(settings.model).toBe('opus');
    expect(settings.permissions.allow).toEqual(['Bash']);
  });
});
