import fs from 'node:fs';
import path from 'node:path';
import type { GeneratorResult, WriteMode } from './index.js';

const GUIDE_CONTENT = `# Copilot Security Guide

> Generated by [aiignore](https://github.com/yjcho9317/aiignore)

## No File-Level Protection Available

GitHub Copilot does **not** have a \`.copilotignore\` file or any file-level
ignore mechanism for individual developers.

### What exists (but doesn't help individual devs):

- **Content Exclusion**: Organization/Enterprise only setting
  - Configured by org admins in GitHub Settings
  - Not available for personal accounts or free plans
  - Does NOT work in Agent mode, Edit mode, or Copilot CLI

### Recommended alternatives:

1. **Keep secrets outside your project directory**
   - Use environment variables from your shell profile
   - Use a secrets manager (1Password CLI, Vault, etc.)

2. **Use .gitignore** (partial protection)
   - Copilot may still read gitignored files for context
   - But it reduces the chance of secrets in suggestions

3. **If you have Business/Enterprise plan**:
   - Ask your org admin to configure Content Exclusion
   - Settings -> Copilot -> Content exclusion -> Add paths

### References:
- [GitHub Docs: Content Exclusion](https://docs.github.com/en/copilot/managing-copilot/configuring-content-exclusions)
`;

export function generateCopilotGuide(
  projectDir: string,
  _patterns: string[],
  mode: WriteMode,
): GeneratorResult {
  const dirPath = path.join(projectDir, '.github');
  const filePath = path.join(dirPath, 'copilot-security-guide.md');

  if (fs.existsSync(filePath) && mode !== 'force') {
    return {
      toolId: 'copilot', toolName: 'GitHub Copilot',
      filePath: '.github/copilot-security-guide.md',
      created: false, skipped: true,
      message: 'Already exists (use --force to overwrite)',
    };
  }

  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }

  fs.writeFileSync(filePath, GUIDE_CONTENT, 'utf-8');

  return {
    toolId: 'copilot', toolName: 'GitHub Copilot',
    filePath: '.github/copilot-security-guide.md',
    created: true, skipped: false,
    message: 'No file-level protection — guide created instead',
  };
}
