import fs from 'node:fs';
import path from 'node:path';
import type { GeneratorResult, WriteMode } from './index.js';

export function generateCursorignore(
  projectDir: string,
  patterns: string[],
  mode: WriteMode,
): GeneratorResult {
  const filePath = path.join(projectDir, '.cursorignore');
  const exists = fs.existsSync(filePath);

  if (exists && mode === 'default') {
    return skipResult('cursor', 'Cursor', '.cursorignore');
  }

  if (exists && mode === 'append') {
    const added = appendPatterns(filePath, patterns);
    return {
      toolId: 'cursor', toolName: 'Cursor', filePath: '.cursorignore',
      created: added > 0, skipped: added === 0,
      message: added > 0 ? `${added} pattern(s) added` : 'No new patterns to add',
    };
  }

  const content = buildIgnoreFile('Cursor', '.cursorignore', patterns, [
    'NOTE: Cursor treats .cursorignore as "best-effort" — not guaranteed.',
    'CVE-2025-59944: case-sensitivity bypass known.',
    'CVE-2025-64110: agent rewrite bypass known.',
  ]);

  fs.writeFileSync(filePath, content, 'utf-8');

  return {
    toolId: 'cursor', toolName: 'Cursor', filePath: '.cursorignore',
    created: true, skipped: false,
    message: '"best-effort" — not guaranteed',
  };
}

export function buildIgnoreFile(
  toolName: string,
  fileName: string,
  patterns: string[],
  warnings: string[] = [],
): string {
  const lines: string[] = [
    `# ${fileName}`,
    `# Generated by aiignore — https://github.com/yjcho9317/aiignore`,
    `# Protects sensitive files from ${toolName}`,
    '#',
  ];

  if (warnings.length > 0) {
    for (const warn of warnings) {
      lines.push(`# WARNING: ${warn}`);
    }
    lines.push('#');
  }

  lines.push('');

  lines.push('# Secrets & Environment');
  lines.push(...patterns.filter((p) => p.includes('.env') || p.includes('secret') || p.includes('credential') || p.includes('token')));
  lines.push('');

  lines.push('# Keys & Certificates');
  lines.push(...patterns.filter((p) =>
    p.includes('.pem') || p.includes('.key') || p.includes('.p12') ||
    p.includes('.pfx') || p.includes('.jks') || p.includes('.keystore') ||
    p.includes('.crt') || p.includes('.cer') || p.includes('.ca-bundle'),
  ));
  lines.push('');

  lines.push('# SSH');
  lines.push(...patterns.filter((p) =>
    p.includes('ssh') || p.includes('id_rsa') || p.includes('id_ed25519') ||
    p.includes('id_ecdsa') || p.includes('known_hosts'),
  ));
  lines.push('');

  lines.push('# Cloud Providers');
  lines.push(...patterns.filter((p) =>
    p.includes('.aws') || p.includes('.gcp') || p.includes('.azure') || p.includes('gcloud'),
  ));
  lines.push('');

  lines.push('# Application Secrets & Database');
  lines.push(...patterns.filter((p) =>
    p.includes('vault') || p.includes('master.key') || p.includes('.secret') ||
    p.includes('.sqlite') || p.includes('.db') || p.includes('dump.sql') ||
    p.includes('.dump') || p.includes('secrets.yml'),
  ));
  lines.push('');

  return lines.join('\n');
}

export function appendPatterns(filePath: string, patterns: string[]): number {
  const existing = fs.readFileSync(filePath, 'utf-8');
  const newPatterns = patterns.filter((p) => !existing.includes(p));
  if (newPatterns.length === 0) return 0;

  const addition = '\n# Added by aiignore\n' + newPatterns.join('\n') + '\n';
  fs.appendFileSync(filePath, addition, 'utf-8');
  return newPatterns.length;
}

export function skipResult(toolId: string, toolName: string, filePath: string): GeneratorResult {
  return {
    toolId, toolName, filePath,
    created: false, skipped: true,
    message: 'Already exists (use --force to overwrite or --append to add patterns)',
  };
}
